name: Kris Wignes
description: Front-End Developer
meta_description: "Front-End Developer"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: http://kriswignes.com/
google_analytics: UA-65288513-4
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url:            'blog url'
author:         'Kris Wignes'
