# Site settings
title: Kris Wignes
description: >
    Kris Wignes
author: Kris Wignes
email: kriswignes@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kriswignes.com/" # the base hostname & protocol for your site
linkedin_username: kriswignes
github_username:  kwignes

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title
sass:
    style: compressed
